"""add_ticket_routing_rules_table

Revision ID: 41b4a96bcf02
Revises: 50022b7ca042
Create Date: 2026-10-02 07:18:41.330857
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b4a96bcf02'
down_revision: Union[str, None] = '50022b7ca042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_routing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('assigned_role', sa.String(length=50), nullable=False),
    sa.Column('assignee_name', sa.String(length=255), nullable=True),
    sa.Column('assignee_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_routing_rules_category'), 'ticket_routing_rules', ['category'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_routing_rules_category'), table_name='ticket_routing_rules')
    op.drop_table('ticket_routing_rules')
    # ### end Alembic commands ###
