"""add_is_preview_to_lessons

Revision ID: 4ee051043ec8
Revises: 9ce22ea4f112
Create Date: 2026-08-29 09:48:50.622037
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee051043ec8'
down_revision: Union[str, None] = '9ce22ea4f112'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('is_preview', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'is_preview')
    # ### end Alembic commands ###
