"""Add support ticket updates

Revision ID: 50022b7ca042
Revises: 7e38c5dab690
Create Date: 2026-10-01 16:38:57.473711
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50022b7ca042'
down_revision: Union[str, None] = '7e38c5dab690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_reads',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticket_id', 'user_id')
    )
    op.drop_column('courses', 'skills')
    op.drop_column('courses', 'learning_outcomes')
    op.add_column('support_tickets', sa.Column('ticket_number', sa.String(length=50), nullable=False))
    op.add_column('support_tickets', sa.Column('assigned_team', sa.String(length=50), nullable=False))
    op.add_column('support_tickets', sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('support_tickets', sa.Column('last_activity_by', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'support_tickets', ['ticket_number'])
    op.create_foreign_key(None, 'support_tickets', 'users', ['last_activity_by'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'payout_account_number')
    op.drop_column('users', 'payout_account_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payout_account_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('payout_account_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'support_tickets', type_='foreignkey')
    op.drop_constraint(None, 'support_tickets', type_='unique')
    op.drop_column('support_tickets', 'last_activity_by')
    op.drop_column('support_tickets', 'last_activity_at')
    op.drop_column('support_tickets', 'assigned_team')
    op.drop_column('support_tickets', 'ticket_number')
    op.add_column('courses', sa.Column('learning_outcomes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('ticket_reads')
    # ### end Alembic commands ###
