"""Add Wishlist model

Revision ID: 608b239bd38a
Revises: edd14ffd6ab9
Create Date: 2026-08-29 14:32:47.105383
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '608b239bd38a'
down_revision: Union[str, None] = 'edd14ffd6ab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'course_id', name='uix_learner_course_wishlist')
    )
    op.drop_table('transactions')
    op.drop_table('instructor_payouts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instructor_payouts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('instructor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('released_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], name='instructor_payouts_instructor_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='instructor_payouts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('learner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('refund_status', sa.VARCHAR(length=50), server_default=sa.text("'none'::character varying"), autoincrement=False, nullable=False),
    sa.Column('refund_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('included_in_payout_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='transactions_course_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['included_in_payout_id'], ['instructor_payouts.id'], name='transactions_included_in_payout_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], name='transactions_learner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='transactions_pkey')
    )
    op.drop_table('wishlists')
    # ### end Alembic commands ###
