"""Add branch_id to support_tickets

Revision ID: 82f9256ce371
Revises: e5d91fecfd6e
Create Date: 2026-10-02 16:33:22.151239
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f9256ce371'
down_revision: Union[str, None] = 'e5d91fecfd6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'support_tickets', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'support_tickets', type_='foreignkey')
    op.drop_column('support_tickets', 'branch_id')
    # ### end Alembic commands ###
