"""Add support tickets

Revision ID: 99f0ddfff895
Revises: 0918c0ffcf56
Create Date: 2026-09-19 18:29:14.867299
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99f0ddfff895'
down_revision: Union[str, None] = '0918c0ffcf56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
