"""Add platform settings and payout fields

Revision ID: 9e0e00774224
Revises: 99f0ddfff895
Create Date: 2026-09-19 18:48:53.851898
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0e00774224'
down_revision: Union[str, None] = '99f0ddfff895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('payout_account_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('payout_account_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'payout_account_number')
    op.drop_column('users', 'payout_account_name')
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
