"""add_recording_fields_to_live_classes

Revision ID: b6212267563c
Revises: 8bb00448a1c6
Create Date: 2026-09-05 13:33:53.058817
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6212267563c'
down_revision: Union[str, None] = '8bb00448a1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_classes', sa.Column('recording_url', sa.String(length=512), nullable=True))
    op.add_column('live_classes', sa.Column('recording_status', sa.String(length=50), nullable=False, server_default='none'))
    op.add_column('live_classes', sa.Column('recording_uploaded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('live_classes', 'recording_uploaded_at')
    op.drop_column('live_classes', 'recording_status')
    op.drop_column('live_classes', 'recording_url')
    # ### end Alembic commands ###
