"""Add learning_outcomes and skills to Course

Revision ID: b785c9781006
Revises: 8bb00448a1c6
Create Date: 2026-09-05 12:33:18.595650
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b785c9781006'
down_revision: Union[str, None] = '8bb00448a1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('learning_outcomes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('courses', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('enrollments', 'payout_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_foreign_key(None, 'enrollments', 'users', ['approved_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.alter_column('enrollments', 'payout_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('courses', 'skills')
    op.drop_column('courses', 'learning_outcomes')
    # ### end Alembic commands ###
