"""add payout status

Revision ID: c71869c69281
Revises: 9b60958c6eff
Create Date: 2026-08-14 09:28:01.084426
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71869c69281'
down_revision: Union[str, None] = '9b60958c6eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollments', sa.Column('payout_status', sa.String(length=20), nullable=False, server_default='pending'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollments', 'payout_status')
    # ### end Alembic commands ###
