"""Add Transaction model

Revision ID: cd761676308e
Revises: 56c4fb1d4a80
Create Date: 2026-08-28 18:52:42.829838
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd761676308e'
down_revision: Union[str, None] = '56c4fb1d4a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('learner_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('audit_logs', sa.Column('actor_user_id', sa.UUID(), nullable=True))
    op.add_column('audit_logs', sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('audit_logs', 'target_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('audit_logs', 'target_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_id', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'users', ['actor_user_id'], ['id'], ondelete='SET NULL')
    op.drop_column('audit_logs', 'actor_id')
    op.drop_column('audit_logs', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.create_index('ix_audit_logs_actor_id', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.alter_column('audit_logs', 'target_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('audit_logs', 'target_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('audit_logs', 'timestamp')
    op.drop_column('audit_logs', 'actor_user_id')
    op.drop_table('transactions')
    # ### end Alembic commands ###
