"""Add branches and org logic

Revision ID: e5d91fecfd6e
Revises: f3a221d5ffa9
Create Date: 2026-10-02 16:19:30.244975
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d91fecfd6e'
down_revision: Union[str, None] = 'f3a221d5ffa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_routing_rules', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.drop_index('ix_ticket_routing_rules_category', table_name='ticket_routing_rules')
    op.create_index(op.f('ix_ticket_routing_rules_category'), 'ticket_routing_rules', ['category'], unique=False)
    op.create_unique_constraint('uq_ticket_routing_rule_category_branch', 'ticket_routing_rules', ['category', 'branch_id'])
    op.create_foreign_key(None, 'ticket_routing_rules', 'branches', ['branch_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('branch_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'branch_id')
    op.drop_constraint(None, 'ticket_routing_rules', type_='foreignkey')
    op.drop_constraint('uq_ticket_routing_rule_category_branch', 'ticket_routing_rules', type_='unique')
    op.drop_index(op.f('ix_ticket_routing_rules_category'), table_name='ticket_routing_rules')
    op.create_index('ix_ticket_routing_rules_category', 'ticket_routing_rules', ['category'], unique=True)
    op.drop_column('ticket_routing_rules', 'branch_id')
    # ### end Alembic commands ###
