"""Add refund fields to transactions

Revision ID: fa4fa25c5593
Revises: cd761676308e
Create Date: 2026-08-29 08:21:54.935900
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa4fa25c5593'
down_revision: Union[str, None] = 'cd761676308e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('refund_status', sa.String(length=50), nullable=False, server_default='none'))
    op.add_column('transactions', sa.Column('refund_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'refund_reason')
    op.drop_column('transactions', 'refund_status')
    # ### end Alembic commands ###
